# Generated by Django 2.2.13 on 2022-06-26 14:14

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('knowledge', 'مدیریت دانش'), ('center', 'مرکز رشد'), ('resume', 'امور محققین'), ('future', 'آینده پژوهی')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, max_length=255, null=True, upload_to=accounts.models.get_avatar_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mobile_number', models.CharField(max_length=11, unique=True, verbose_name='تلفن همراه')),
                ('permissions', models.ManyToManyField(blank=True, to='accounts.Permission', verbose_name='دسترسی ها')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
