# Generated by Django 2.2.13 on 2022-06-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('knowledge', 'مدیریت دانش'), ('center', 'مرکز رشد'), ('resume', 'امور محققین'), ('future', 'آینده پژوهی')], max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='accounts.Permission', verbose_name='دسترسی ها'),
        ),
    ]
