# Generated by Django 2.2.13 on 2022-05-27 07:53

from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('organization_code', models.CharField(max_length=255)),
                ('center', models.CharField(choices=[('Sample', 'نمونه')], max_length=255)),
                ('field', models.CharField(choices=[('Sample', 'نمونه')], max_length=255)),
                ('type', models.CharField(choices=[('Article', 'مقاله'), ('Resume', 'رزومه')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(max_length=255, upload_to=documents.models.get_attachment_directory_path)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.Document')),
                ('held_at', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('sample', 'نمونه')], max_length=255)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('documents.document',),
        ),
        migrations.CreateModel(
            name='CoWork',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.Document')),
                ('address', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('documents.document',),
        ),
        migrations.CreateModel(
            name='Future',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.Document')),
                ('presented_at', models.DateTimeField()),
                ('future_type', models.CharField(choices=[('sample', 'نمونه')], max_length=255)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('documents.document',),
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.Document')),
                ('presented_at', models.DateTimeField()),
                ('page_number', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('documents.document',),
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.Document')),
                ('finished_at', models.DateTimeField()),
                ('manager', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('documents.document',),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.Document')),
                ('entrance_year', models.IntegerField()),
                ('measure', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('documents.document',),
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.Document')),
                ('university', models.CharField(max_length=255)),
                ('measure', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('documents.document',),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.Document')),
                ('location', models.CharField(max_length=255)),
                ('visited_at', models.DateTimeField()),
                ('participant_number', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('documents.document',),
        ),
        migrations.AddField(
            model_name='document',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='attachments', to='documents.DocumentAttachment'),
        ),
        migrations.AddField(
            model_name='document',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_documents.document_set+', to='contenttypes.ContentType'),
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.Document')),
                ('judges', models.TextField()),
                ('started_at', models.DateTimeField()),
                ('meeting_number', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('workshop_type', models.CharField(choices=[('sample', 'نمونه')], max_length=255)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workshop_producer', to='documents.Resume')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('documents.document',),
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.Document')),
                ('judges', models.TextField()),
                ('presented_at', models.DateTimeField()),
                ('participants_number', models.IntegerField()),
                ('assessment_result', models.CharField(max_length=255)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seminar_producer', to='documents.Resume')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('documents.document',),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.Document')),
                ('presented_at', models.DateTimeField()),
                ('related_project', models.CharField(max_length=255)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_producer', to='documents.Resume')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('documents.document',),
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.Document')),
                ('declared_at', models.DateTimeField()),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_producer', to='documents.Resume')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('documents.document',),
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.Document')),
                ('judges', models.TextField()),
                ('presented_at', models.DateTimeField()),
                ('assessment_result', models.CharField(max_length=255)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='idea_producer', to='documents.Resume')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('documents.document',),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.Document')),
                ('judges', models.TextField()),
                ('presented_at', models.DateTimeField()),
                ('assessment_result', models.CharField(max_length=255)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experience_producer', to='documents.Resume')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('documents.document',),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.Document')),
                ('fipa', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField()),
                ('publisher', models.CharField(max_length=255)),
                ('assessment_result', models.CharField(max_length=255)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_producer', to='documents.Resume')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('documents.document',),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.Document')),
                ('key_words', models.TextField()),
                ('published_at', models.DateTimeField()),
                ('publish_type', models.CharField(choices=[('Paper', 'مجله'), ('Conference', 'کنفرانس')], max_length=255)),
                ('publish_level', models.CharField(choices=[('ISI', 'ISI'), ('ISC', 'ISC'), ('Research', 'علمی-پژوهشی'), ('Extension', 'علمی-ترویجی'), ('Specialized', 'علمی-تخصصی')], max_length=255)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='article_producer', to='documents.Resume')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('documents.document',),
        ),
    ]
