# Generated by Django 2.2.13 on 2022-05-27 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='producer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='thesis_producer', to='documents.Resume'),
            preserve_default=False,
        ),
    ]
