# Generated by Django 2.2.13 on 2022-06-29 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_resume_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
