# Generated by Django 2.2.13 on 2022-05-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_thesis_producer'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='judges',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='field',
            field=models.CharField(choices=[('Sample', 'نمونه'), ('No Field', 'بدون فیلد')], max_length=255),
        ),
    ]
