# Generated by Django 2.2.13 on 2022-06-08 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20220608_0742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centerpersonnel',
            old_name='firs_name',
            new_name='first_name',
        ),
    ]
