# Generated by Django 2.2.13 on 2022-06-30 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_order_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='center', to='documents.Center'),
        ),
    ]
