# Generated by Django 2.2.13 on 2022-06-24 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20220608_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='producer',
        ),
        migrations.AddField(
            model_name='article',
            name='judges',
            field=models.ManyToManyField(related_name='article_judges', to='documents.Resume'),
        ),
        migrations.AddField(
            model_name='article',
            name='producers',
            field=models.ManyToManyField(related_name='article_producers', to='documents.Resume'),
        ),
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_level',
            field=models.CharField(choices=[('ISI', 'ISI'), ('ISC', 'ISC'), ('Research', 'علمی-پژوهشی'), ('Extension', 'علمی-ترویجی'), ('Specialized', 'علمی-تخصصی'), ('Sepah', 'سپاه'), ('Martial', 'نیروهای مسلح'), ('National', 'ملی'), ('International', 'بین المللی')], max_length=255),
        ),
        migrations.RemoveField(
            model_name='book',
            name='judges',
        ),
        migrations.AddField(
            model_name='book',
            name='judges',
            field=models.ManyToManyField(related_name='book_judges', to='documents.Resume'),
        ),
        migrations.AlterField(
            model_name='document',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='center', to='documents.Center'),
        ),
        migrations.AlterField(
            model_name='document',
            name='field',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='organization_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='experience',
            name='judges',
        ),
        migrations.AddField(
            model_name='experience',
            name='judges',
            field=models.ManyToManyField(related_name='experience_judges', to='documents.Resume'),
        ),
        migrations.RemoveField(
            model_name='idea',
            name='judges',
        ),
        migrations.AddField(
            model_name='idea',
            name='judges',
            field=models.ManyToManyField(related_name='idea_judges', to='documents.Resume'),
        ),
        migrations.AlterField(
            model_name='report',
            name='related_project',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='judges',
        ),
        migrations.AddField(
            model_name='seminar',
            name='judges',
            field=models.ManyToManyField(related_name='seminar_judges', to='documents.Resume'),
        ),
    ]
