# Generated by Django 2.2.13 on 2022-05-27 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20220527_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='field',
            field=models.CharField(choices=[('Sample', 'نمونه'), ('No Field', 'بدون حوزه')], max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('Article', 'مقاله'), ('Resume', 'رزومه'), ('Book', 'کتاب'), ('Experience', 'تجربه'), ('Thesis', 'پایان نامه')], max_length=255),
        ),
    ]
