# Generated by Django 2.2.13 on 2022-06-25 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20220624_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('Article', 'مقاله'), ('Resume', 'رزومه'), ('Book', 'کتاب'), ('Experience', 'تجربه'), ('Thesis', 'پایان نامه'), ('Idea', 'ایده'), ('Seminar', 'سمینار'), ('Workshop', 'کارگاه'), ('Conference', 'کنفرانس'), ('Visit', 'بازدید'), ('Project', 'پروژه'), ('Manual', 'دستورالعمل'), ('Report', 'گزارش'), ('Journal', 'فصلنامه'), ('Future', 'آینده پژوهی'), ('CoWork', 'همکاری'), ('Order', 'حکم')], max_length=255),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.Document')),
                ('issued_at', models.DateTimeField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_receiver', to='documents.Resume')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('documents.document',),
        ),
    ]
