# Generated by Django 2.2.13 on 2022-06-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20220630_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='future',
            name='other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_level',
            field=models.CharField(choices=[('ISI', 'ISI'), ('ISC', 'ISC'), ('Journal', 'فصلنامه'), ('Research', 'علمی-پژوهشی'), ('Extension', 'علمی-ترویجی'), ('Specialized', 'علمی-تخصصی'), ('Sepah', 'سپاه'), ('Martial', 'نیروهای مسلح'), ('National', 'ملی'), ('International', 'بین المللی')], max_length=255),
        ),
        migrations.AlterField(
            model_name='future',
            name='future_type',
            field=models.CharField(choices=[('Rasadi', 'گزارش رصدی'), ('Info', 'اینفوگرافی'), ('Dide', 'دیده بان'), ('Organ', 'گزارش سازمانی'), ('Other', 'سایر')], max_length=255),
        ),
    ]
