# Generated by Django 2.2.13 on 2022-05-27 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20220527_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thesis',
            old_name='published_at',
            new_name='presented_at',
        ),
    ]
