# Generated by Django 2.2.13 on 2022-08-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20220630_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_attachments',
            field=models.ManyToManyField(blank=True, related_name='end_project_attachments', to='documents.DocumentAttachment'),
        ),
        migrations.AddField(
            model_name='project',
            name='middle_attachments',
            field=models.ManyToManyField(blank=True, related_name='middle_project_attachments', to='documents.DocumentAttachment'),
        ),
    ]
