# Generated by Django 2.2.13 on 2022-05-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20220527_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='level',
            new_name='conference_level',
        ),
        migrations.RenameField(
            model_name='seminar',
            old_name='participants_number',
            new_name='participant_number',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='judges',
        ),
        migrations.AddField(
            model_name='workshop',
            name='participant_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('Article', 'مقاله'), ('Resume', 'رزومه'), ('Book', 'کتاب'), ('Experience', 'تجربه'), ('Thesis', 'پایان نامه'), ('Idea', 'ایده'), ('Seminar', 'سمینار'), ('ٌWorkshop', 'کارگاه'), ('Conference', 'کنفرانس'), ('Visit', 'بازدید')], max_length=255),
        ),
    ]
