# Generated by Django 2.2.13 on 2022-06-26 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20220625_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invention',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.Document')),
                ('key_words', models.TextField()),
                ('registered_at', models.DateTimeField()),
                ('producers', models.ManyToManyField(related_name='invention_producers', to='documents.Resume')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('documents.document',),
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.Document')),
                ('elite_received_at', models.DateTimeField()),
                ('order_issued_at', models.DateTimeField()),
                ('issue_code', models.CharField(max_length=255)),
                ('scientific_rank', models.CharField(max_length=255)),
                ('father', models.CharField(max_length=255)),
                ('profile_type', models.CharField(max_length=255)),
                ('necessary_condition', models.TextField()),
                ('sufficient_condition', models.TextField()),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_resume', to='documents.Resume')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('documents.document',),
        ),
    ]
