# Generated by Django 2.2.13 on 2022-05-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20220527_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('Article', 'مقاله'), ('Resume', 'رزومه'), ('Book', 'کتاب'), ('Experience', 'تجربه'), ('Thesis', 'پایان نامه'), ('Idea', 'ایده'), ('Seminar', 'سمینار'), ('Workshop', 'کارگاه'), ('Conference', 'کنفرانس'), ('Visit', 'بازدید')], max_length=255),
        ),
    ]
