# Generated by Django 2.2.13 on 2022-08-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20220805_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='degree',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='entrance_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='measure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
