# Generated by Django 2.2.13 on 2022-06-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_assessment_invention'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invention',
            name='key_words',
        ),
        migrations.AddField(
            model_name='invention',
            name='project_title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('Article', 'مقاله'), ('Resume', 'رزومه'), ('Book', 'کتاب'), ('Experience', 'تجربه'), ('Thesis', 'پایان نامه'), ('Idea', 'ایده'), ('Seminar', 'سمینار'), ('Workshop', 'کارگاه'), ('Conference', 'کنفرانس'), ('Visit', 'بازدید'), ('Project', 'پروژه'), ('Manual', 'دستورالعمل'), ('Report', 'گزارش'), ('Journal', 'فصلنامه'), ('Future', 'آینده پژوهی'), ('CoWork', 'همکاری'), ('Order', 'حکم'), ('Invention', 'ثبت اختراع'), ('Assessment', 'ارزیابی')], max_length=255),
        ),
    ]
