# Generated by Django 2.2.13 on 2022-05-27 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_auto_20220527_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.Document')),
                ('finished_at', models.DateTimeField()),
                ('description', models.TextField()),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_manager', to='documents.Resume')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('documents.document',),
        ),
        migrations.AlterField(
            model_name='conference',
            name='conference_level',
            field=models.CharField(choices=[('Citywid', 'شهری'), ('Regional', 'استانی'), ('Countrywide', 'کشوری'), ('Wordwide', 'بین المللی')], max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='center',
            field=models.CharField(choices=[('center-1', 'مرکز نمونه ۱'), ('center-2', 'مرکز نمونه ۲')], max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='field',
            field=models.CharField(choices=[('field-1', 'حوزه نمونه ۱'), ('field-2', 'حوزه نمونه ۲'), ('field-3', 'حوزه نمونه ۳'), ('No Field', 'بدون حوزه')], max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('Article', 'مقاله'), ('Resume', 'رزومه'), ('Book', 'کتاب'), ('Experience', 'تجربه'), ('Thesis', 'پایان نامه'), ('Idea', 'ایده'), ('Seminar', 'سمینار'), ('Workshop', 'کارگاه'), ('Conference', 'کنفرانس'), ('Visit', 'بازدید'), ('Project', 'پروژه'), ('Manual', 'دستورالعمل'), ('Report', 'گزارش')], max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='related_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_project', to='documents.Project'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='workshop_type',
            field=models.CharField(choices=[('Technical', 'کارگاه فنی'), ('Scientific', 'کارگاه علمی'), ('Course', 'دوره آموزشی')], max_length=255),
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
