# Generated by Django 2.2.13 on 2022-08-12 13:00

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_resume_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=documents.models.get_center_avatar_directory_path),
        ),
    ]
