# Generated by Django 2.2.13 on 2022-08-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_center_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='judges',
            field=models.ManyToManyField(blank=True, null=True, related_name='article_judges', to='documents.Resume'),
        ),
        migrations.AlterField(
            model_name='article',
            name='key_words',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='judges',
            field=models.ManyToManyField(blank=True, null=True, related_name='book_judges', to='documents.Resume'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='judges',
            field=models.ManyToManyField(blank=True, null=True, related_name='experience_judges', to='documents.Resume'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='judges',
            field=models.ManyToManyField(blank=True, null=True, related_name='idea_judges', to='documents.Resume'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='judges',
            field=models.ManyToManyField(blank=True, null=True, related_name='seminar_judges', to='documents.Resume'),
        ),
    ]
