# Generated by Django 2.2.13 on 2022-05-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_auto_20220527_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='cowork',
            name='cowork_type',
            field=models.CharField(choices=[('Company', 'شرکت'), ('University', 'دانشگاه')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cowork',
            name='person_type',
            field=models.CharField(choices=[('Real', 'حقیقی'), ('Legal', 'حقوقی')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
