# Generated by Django 2.2.13 on 2022-05-27 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_auto_20220527_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='future',
            name='producer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='future_producer', to='documents.Resume'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
