# Generated by Django 2.2.13 on 2022-08-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_auto_20220819_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='necessary_condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='sufficient_condition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
