# Generated by Django 2.2.13 on 2022-05-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_auto_20220527_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('Article', 'مقاله'), ('Resume', 'رزومه'), ('Book', 'کتاب'), ('Experience', 'تجربه'), ('Thesis', 'پایان نامه'), ('Idea', 'ایده'), ('Seminar', 'سمینار'), ('Workshop', 'کارگاه'), ('Conference', 'کنفرانس'), ('Visit', 'بازدید'), ('Project', 'پروژه'), ('Manual', 'دستورالعمل'), ('Report', 'گزارش'), ('Journal', 'فصلنامه'), ('Future', 'آینده پژوهی'), ('CoWork', 'همکاری')], max_length=255),
        ),
    ]
