# Generated by Django 2.2.13 on 2022-08-27 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_auto_20220825_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='cowork',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
