# Generated by Django 2.2.13 on 2022-08-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_cowork_started_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='producer',
        ),
        migrations.AddField(
            model_name='book',
            name='producers',
            field=models.ManyToManyField(related_name='book_producers', to='documents.Resume'),
        ),
    ]
