# Generated by Django 2.2.13 on 2022-06-06 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220606_1226'),
        ('documents', '0012_auto_20220527_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cowork',
            name='description',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='center',
            field=models.CharField(choices=[('center-11', 'م.حاجت زاه(شناوری)'), ('center-12', 'م.تهرانی(سلاح و مهمات)'), ('center-13', 'ش.رضایی(موشکی)'), ('center-14', 'ش.محمدیها(هوادریا)'), ('center-15', 'ش.چمران(الکترونیک)'), ('center-16', 'ش.همدانی(پدافند)'), ('center-17', 'م.جلالی(مواد)'), ('center-18', 'ش.مهدوی(فناوری)'), ('center-19', 'مد.نوآوری(مد.دانش-آینده پژوهی)'), ('center-20', 'مد.تحقیقات(تحقیقات)'), ('center-21', 'ش.ناظری(موتور)'), ('center-22', 'زیرسطحی'), ('center-23', 'ش.آبسالان(فیزیک دریا)'), ('center-24', 'ش.عسگری(رادار)'), ('center-25', 'بازرسی-بهداری')], max_length=255),
        ),
    ]
