# Generated by Django 2.2.13 on 2022-08-29 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_auto_20220827_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowork',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
