# Generated by Django 2.2.13 on 2022-08-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_auto_20220829_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
