# Generated by Django 2.2.13 on 2022-06-07 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('documents', '0014_auto_20220606_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Core', 'هسته'), ('TechUnit', 'واحد فناورانه'), ('Comapny', 'شرکت')], max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('manager', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('establish_year', models.IntegerField()),
                ('number', models.IntegerField()),
                ('activity_field', models.CharField(max_length=255)),
                ('professional_field', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachments', models.ManyToManyField(blank=True, related_name='center_attachments', to='documents.DocumentAttachment')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('centerdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.CenterData')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('documents.centerdata',),
        ),
        migrations.CreateModel(
            name='Core',
            fields=[
                ('centerdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.CenterData')),
                ('preDev_number', models.IntegerField(blank=True, null=True)),
                ('first_level_number', models.IntegerField(blank=True, null=True)),
                ('second_level_number', models.IntegerField(blank=True, null=True)),
                ('third_level_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('documents.centerdata',),
        ),
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('centerdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.CenterData')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('documents.centerdata',),
        ),
        migrations.CreateModel(
            name='CenterProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachments', models.ManyToManyField(blank=True, related_name='center_project_attachments', to='documents.DocumentAttachment')),
            ],
        ),
        migrations.CreateModel(
            name='CenterPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_code', models.CharField(max_length=255)),
                ('birth_year', models.IntegerField()),
                ('measure', models.CharField(max_length=255)),
                ('sub_measure', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('address', models.TextField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('basij_entrance_year', models.IntegerField()),
                ('basij_city', models.CharField(max_length=255)),
                ('pre_empowerment', models.CharField(max_length=255)),
                ('com_empowerment', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachments', models.ManyToManyField(blank=True, related_name='center_personnel_attachments', to='documents.DocumentAttachment')),
            ],
        ),
        migrations.AddField(
            model_name='centerdata',
            name='personnels',
            field=models.ManyToManyField(blank=True, related_name='personnel', to='documents.CenterPerson'),
        ),
        migrations.AddField(
            model_name='centerdata',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_documents.centerdata_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='centerdata',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='projects', to='documents.CenterProject'),
        ),
    ]
