# Generated by Django 2.2.13 on 2022-06-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_auto_20220607_1840'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CenterPerson',
            new_name='CenterPersonnel',
        ),
        migrations.RemoveField(
            model_name='core',
            name='first_level_number',
        ),
        migrations.RemoveField(
            model_name='core',
            name='preDev_number',
        ),
        migrations.RemoveField(
            model_name='core',
            name='second_level_number',
        ),
        migrations.RemoveField(
            model_name='core',
            name='third_level_number',
        ),
        migrations.AddField(
            model_name='centerproject',
            name='level',
            field=models.CharField(choices=[('predev', 'پیش رشد'), ('first', 'سطح یک'), ('second', 'سطح دو'), ('third', 'سطح سه')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
