# Generated by Django 2.2.13 on 2022-09-23 10:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_auto_20220923_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='verification',
            field=models.CharField(choices=[('verified', 'تایید شد'), ('not-verified', 'تایید نشد')], default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
