# Generated by Django 2.2.13 on 2022-06-08 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_auto_20220608_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centerpersonnel',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='centerpersonnel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='centerproject',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='centerproject',
            name='description',
        ),
    ]
