# Generated by Django 2.2.13 on 2022-11-03 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_auto_20221001_0434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop',
            old_name='meeting_number',
            new_name='duration',
        ),
        migrations.RemoveField(
            model_name='article',
            name='judges',
        ),
        migrations.RemoveField(
            model_name='book',
            name='judges',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='judges',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='future',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='judges',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='manual',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='report',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='judges',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='producer',
        ),
        migrations.AddField(
            model_name='experience',
            name='producers',
            field=models.ManyToManyField(related_name='experience_producers', to='documents.Resume'),
        ),
        migrations.AddField(
            model_name='future',
            name='producers',
            field=models.ManyToManyField(related_name='future_producers', to='documents.Resume'),
        ),
        migrations.AddField(
            model_name='idea',
            name='producers',
            field=models.ManyToManyField(related_name='idea_producers', to='documents.Resume'),
        ),
        migrations.AddField(
            model_name='manual',
            name='producers',
            field=models.ManyToManyField(related_name='manual_producers', to='documents.Resume'),
        ),
        migrations.AddField(
            model_name='order',
            name='judges',
            field=models.ManyToManyField(related_name='order_judges', to='documents.Resume'),
        ),
        migrations.AddField(
            model_name='report',
            name='producers',
            field=models.ManyToManyField(related_name='report_producers', to='documents.Resume'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='producers',
            field=models.ManyToManyField(related_name='seminar_producers', to='documents.Resume'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='finished_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_level',
            field=models.CharField(blank=True, choices=[('ISI', 'ISI'), ('ISC', 'ISC'), ('Research', 'علمی-پژوهشی'), ('Extension', 'علمی-ترویجی'), ('Specialized', 'علمی-تخصصی'), ('Martial', 'نیروهای مسلح'), ('National', 'ملی'), ('International', 'بین المللی')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_type',
            field=models.CharField(blank=True, choices=[('Paper', 'مجله'), ('Conference', 'کنفرانس')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='assessment_result',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='conference_level',
            field=models.CharField(choices=[('Organizational', 'سازمانی'), ('Martial', 'نیروهای مسلح'), ('National', 'ملی'), ('International', 'بین المللی')], max_length=255),
        ),
        migrations.AlterField(
            model_name='cowork',
            name='cowork_type',
            field=models.CharField(blank=True, choices=[('Company', 'شرکت'), ('University', 'دانشگاه')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='assessment_result',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='future',
            name='presented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='assessment_result',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invention',
            name='project_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='related_project',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='assessment_result',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='participant_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
