# Generated by Django 2.2.13 on 2022-11-06 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0019_auto_20221103_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='father',
        ),
    ]
